/* Generated by Yosys 0.58+35 (git sha1 89f32a415, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module spi_master(clk, rst_n, start, data_in, data_out, busy, done, sclk, mosi, cs_n, miso);
  input clk;
  wire clk;
  input rst_n;
  wire rst_n;
  input start;
  wire start;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  output busy;
  wire busy;
  output done;
  wire done;
  output sclk;
  wire sclk;
  output mosi;
  wire mosi;
  output cs_n;
  wire cs_n;
  input miso;
  wire miso;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire [1:0] _302_;
  wire [3:0] bit_cnt;
  wire [31:0] clk_cnt;
  wire [7:0] data_reg;
  wire done_flag;
  wire [7:0] shift_rx;
  wire [1:0] state;
  INVX1 _303_ (
    .A(busy),
    .Y(_067_)
  );
  INVX1 _304_ (
    .A(clk_cnt[3]),
    .Y(_068_)
  );
  INVX1 _305_ (
    .A(clk_cnt[4]),
    .Y(_069_)
  );
  INVX1 _306_ (
    .A(clk_cnt[7]),
    .Y(_070_)
  );
  INVX1 _307_ (
    .A(clk_cnt[8]),
    .Y(_071_)
  );
  INVX1 _308_ (
    .A(clk_cnt[9]),
    .Y(_072_)
  );
  INVX1 _309_ (
    .A(clk_cnt[11]),
    .Y(_073_)
  );
  INVX1 _310_ (
    .A(clk_cnt[12]),
    .Y(_074_)
  );
  INVX1 _311_ (
    .A(clk_cnt[13]),
    .Y(_075_)
  );
  INVX1 _312_ (
    .A(clk_cnt[15]),
    .Y(_076_)
  );
  INVX1 _313_ (
    .A(clk_cnt[16]),
    .Y(_077_)
  );
  INVX1 _314_ (
    .A(clk_cnt[17]),
    .Y(_078_)
  );
  INVX1 _315_ (
    .A(clk_cnt[19]),
    .Y(_079_)
  );
  INVX1 _316_ (
    .A(clk_cnt[20]),
    .Y(_080_)
  );
  INVX1 _317_ (
    .A(clk_cnt[21]),
    .Y(_081_)
  );
  INVX1 _318_ (
    .A(clk_cnt[23]),
    .Y(_082_)
  );
  INVX1 _319_ (
    .A(clk_cnt[24]),
    .Y(_083_)
  );
  INVX1 _320_ (
    .A(clk_cnt[25]),
    .Y(_084_)
  );
  INVX1 _321_ (
    .A(clk_cnt[27]),
    .Y(_085_)
  );
  INVX1 _322_ (
    .A(clk_cnt[28]),
    .Y(_086_)
  );
  INVX1 _323_ (
    .A(clk_cnt[31]),
    .Y(_087_)
  );
  INVX1 _324_ (
    .A(state[0]),
    .Y(_088_)
  );
  INVX1 _325_ (
    .A(state[1]),
    .Y(_089_)
  );
  INVX1 _326_ (
    .A(bit_cnt[2]),
    .Y(_090_)
  );
  INVX1 _327_ (
    .A(sclk),
    .Y(_091_)
  );
  INVX1 _328_ (
    .A(done_flag),
    .Y(_092_)
  );
  INVX1 _329_ (
    .A(miso),
    .Y(_093_)
  );
  NOR2X1 _330_ (
    .A(_088_),
    .B(state[1]),
    .Y(_094_)
  );
  NAND2X1 _331_ (
    .A(sclk),
    .B(_094_),
    .Y(_095_)
  );
  NOR2X1 _332_ (
    .A(clk_cnt[23]),
    .B(clk_cnt[24]),
    .Y(_096_)
  );
  NOR2X1 _333_ (
    .A(clk_cnt[25]),
    .B(clk_cnt[26]),
    .Y(_097_)
  );
  AND2X1 _334_ (
    .A(_096_),
    .B(_097_),
    .Y(_098_)
  );
  NOR2X1 _335_ (
    .A(clk_cnt[21]),
    .B(clk_cnt[22]),
    .Y(_099_)
  );
  NOR2X1 _336_ (
    .A(clk_cnt[19]),
    .B(clk_cnt[20]),
    .Y(_100_)
  );
  NAND3X1 _337_ (
    .A(_098_),
    .B(_099_),
    .C(_100_),
    .Y(_101_)
  );
  AOI21X1 _338_ (
    .A(clk_cnt[0]),
    .B(clk_cnt[1]),
    .C(clk_cnt[2]),
    .Y(_102_)
  );
  INVX1 _339_ (
    .A(_102_),
    .Y(_103_)
  );
  NOR2X1 _340_ (
    .A(clk_cnt[28]),
    .B(clk_cnt[29]),
    .Y(_104_)
  );
  NOR2X1 _341_ (
    .A(clk_cnt[27]),
    .B(clk_cnt[30]),
    .Y(_105_)
  );
  NAND3X1 _342_ (
    .A(_102_),
    .B(_104_),
    .C(_105_),
    .Y(_106_)
  );
  NOR2X1 _343_ (
    .A(_101_),
    .B(_106_),
    .Y(_107_)
  );
  NOR2X1 _344_ (
    .A(clk_cnt[7]),
    .B(clk_cnt[8]),
    .Y(_108_)
  );
  NOR2X1 _345_ (
    .A(clk_cnt[9]),
    .B(clk_cnt[10]),
    .Y(_109_)
  );
  AND2X1 _346_ (
    .A(_108_),
    .B(_109_),
    .Y(_110_)
  );
  NOR2X1 _347_ (
    .A(clk_cnt[16]),
    .B(clk_cnt[17]),
    .Y(_111_)
  );
  NOR2X1 _348_ (
    .A(clk_cnt[15]),
    .B(clk_cnt[18]),
    .Y(_112_)
  );
  NOR2X1 _349_ (
    .A(clk_cnt[11]),
    .B(clk_cnt[14]),
    .Y(_113_)
  );
  NAND3X1 _350_ (
    .A(_111_),
    .B(_112_),
    .C(_113_),
    .Y(_114_)
  );
  INVX1 _351_ (
    .A(_114_),
    .Y(_115_)
  );
  NOR2X1 _352_ (
    .A(clk_cnt[12]),
    .B(clk_cnt[13]),
    .Y(_116_)
  );
  NOR2X1 _353_ (
    .A(clk_cnt[4]),
    .B(clk_cnt[5]),
    .Y(_117_)
  );
  NAND3X1 _354_ (
    .A(_115_),
    .B(_116_),
    .C(_117_),
    .Y(_118_)
  );
  NOR2X1 _355_ (
    .A(clk_cnt[3]),
    .B(clk_cnt[6]),
    .Y(_119_)
  );
  NAND3X1 _356_ (
    .A(_107_),
    .B(_110_),
    .C(_119_),
    .Y(_120_)
  );
  OAI21X1 _357_ (
    .A(_118_),
    .B(_120_),
    .C(_087_),
    .Y(_121_)
  );
  AND2X1 _358_ (
    .A(_094_),
    .B(_121_),
    .Y(_122_)
  );
  NAND2X1 _359_ (
    .A(_094_),
    .B(_121_),
    .Y(_123_)
  );
  NOR2X1 _360_ (
    .A(state[1]),
    .B(_122_),
    .Y(_124_)
  );
  NAND2X1 _361_ (
    .A(_095_),
    .B(_124_),
    .Y(_125_)
  );
  NAND2X1 _362_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_126_)
  );
  NOR2X1 _363_ (
    .A(_090_),
    .B(_126_),
    .Y(_127_)
  );
  OR2X1 _364_ (
    .A(_090_),
    .B(_126_),
    .Y(_128_)
  );
  OR2X1 _365_ (
    .A(bit_cnt[3]),
    .B(_128_),
    .Y(_129_)
  );
  INVX1 _366_ (
    .A(_129_),
    .Y(_130_)
  );
  NAND2X1 _367_ (
    .A(_091_),
    .B(_094_),
    .Y(_131_)
  );
  OR2X1 _368_ (
    .A(_121_),
    .B(_131_),
    .Y(_132_)
  );
  NOR2X1 _369_ (
    .A(_130_),
    .B(_132_),
    .Y(_133_)
  );
  OAI21X1 _370_ (
    .A(_125_),
    .B(_133_),
    .C(shift_rx[0]),
    .Y(_134_)
  );
  OR2X1 _371_ (
    .A(_129_),
    .B(_132_),
    .Y(_135_)
  );
  OAI21X1 _372_ (
    .A(_093_),
    .B(_135_),
    .C(_134_),
    .Y(_000_)
  );
  OR2X1 _373_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .Y(_136_)
  );
  AOI21X1 _374_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(bit_cnt[3]),
    .Y(_137_)
  );
  OAI21X1 _375_ (
    .A(bit_cnt[0]),
    .B(bit_cnt[1]),
    .C(_137_),
    .Y(_138_)
  );
  NOR2X1 _376_ (
    .A(bit_cnt[0]),
    .B(_138_),
    .Y(_139_)
  );
  AOI21X1 _377_ (
    .A(bit_cnt[2]),
    .B(_139_),
    .C(_132_),
    .Y(_140_)
  );
  OAI21X1 _378_ (
    .A(_125_),
    .B(_140_),
    .C(shift_rx[1]),
    .Y(_141_)
  );
  NAND2X1 _379_ (
    .A(_090_),
    .B(_126_),
    .Y(_142_)
  );
  AND2X1 _380_ (
    .A(_128_),
    .B(_142_),
    .Y(_143_)
  );
  NAND2X1 _381_ (
    .A(_128_),
    .B(_142_),
    .Y(_144_)
  );
  NOR2X1 _382_ (
    .A(_093_),
    .B(_132_),
    .Y(_145_)
  );
  NAND2X1 _383_ (
    .A(_139_),
    .B(_145_),
    .Y(_146_)
  );
  OAI21X1 _384_ (
    .A(_144_),
    .B(_146_),
    .C(_141_),
    .Y(_001_)
  );
  AND2X1 _385_ (
    .A(bit_cnt[0]),
    .B(_137_),
    .Y(_147_)
  );
  AOI21X1 _386_ (
    .A(bit_cnt[2]),
    .B(_147_),
    .C(_132_),
    .Y(_148_)
  );
  OAI21X1 _387_ (
    .A(_125_),
    .B(_148_),
    .C(shift_rx[2]),
    .Y(_149_)
  );
  NAND2X1 _388_ (
    .A(_145_),
    .B(_147_),
    .Y(_150_)
  );
  OAI21X1 _389_ (
    .A(_144_),
    .B(_150_),
    .C(_149_),
    .Y(_002_)
  );
  NOR2X1 _390_ (
    .A(bit_cnt[3]),
    .B(_136_),
    .Y(_151_)
  );
  AOI21X1 _391_ (
    .A(bit_cnt[2]),
    .B(_151_),
    .C(_132_),
    .Y(_152_)
  );
  OAI21X1 _392_ (
    .A(_125_),
    .B(_152_),
    .C(shift_rx[3]),
    .Y(_153_)
  );
  NAND2X1 _393_ (
    .A(_145_),
    .B(_151_),
    .Y(_154_)
  );
  OAI21X1 _394_ (
    .A(_144_),
    .B(_154_),
    .C(_153_),
    .Y(_003_)
  );
  NAND2X1 _395_ (
    .A(shift_rx[4]),
    .B(_125_),
    .Y(_155_)
  );
  OR2X1 _396_ (
    .A(bit_cnt[3]),
    .B(_127_),
    .Y(_156_)
  );
  NOR2X1 _397_ (
    .A(_126_),
    .B(_156_),
    .Y(_157_)
  );
  MUX2X1 _398_ (
    .A(miso),
    .B(shift_rx[4]),
    .S(_157_),
    .Y(_158_)
  );
  OAI21X1 _399_ (
    .A(_132_),
    .B(_158_),
    .C(_155_),
    .Y(_004_)
  );
  AOI21X1 _400_ (
    .A(_090_),
    .B(_139_),
    .C(_132_),
    .Y(_159_)
  );
  OAI21X1 _401_ (
    .A(_125_),
    .B(_159_),
    .C(shift_rx[5]),
    .Y(_160_)
  );
  OAI21X1 _402_ (
    .A(_143_),
    .B(_146_),
    .C(_160_),
    .Y(_005_)
  );
  AOI21X1 _403_ (
    .A(_090_),
    .B(_147_),
    .C(_132_),
    .Y(_161_)
  );
  OAI21X1 _404_ (
    .A(_125_),
    .B(_161_),
    .C(shift_rx[6]),
    .Y(_162_)
  );
  OAI21X1 _405_ (
    .A(_143_),
    .B(_150_),
    .C(_162_),
    .Y(_006_)
  );
  AOI21X1 _406_ (
    .A(_090_),
    .B(_151_),
    .C(_132_),
    .Y(_163_)
  );
  OAI21X1 _407_ (
    .A(_125_),
    .B(_163_),
    .C(shift_rx[7]),
    .Y(_164_)
  );
  OAI21X1 _408_ (
    .A(_143_),
    .B(_154_),
    .C(_164_),
    .Y(_007_)
  );
  NAND2X1 _409_ (
    .A(_089_),
    .B(start),
    .Y(_165_)
  );
  NOR2X1 _410_ (
    .A(state[0]),
    .B(_165_),
    .Y(_166_)
  );
  OR2X1 _411_ (
    .A(state[0]),
    .B(_165_),
    .Y(_167_)
  );
  MUX2X1 _412_ (
    .A(data_reg[0]),
    .B(data_in[0]),
    .S(_167_),
    .Y(_168_)
  );
  INVX1 _413_ (
    .A(_168_),
    .Y(_008_)
  );
  MUX2X1 _414_ (
    .A(data_reg[1]),
    .B(data_in[1]),
    .S(_167_),
    .Y(_169_)
  );
  INVX1 _415_ (
    .A(_169_),
    .Y(_009_)
  );
  MUX2X1 _416_ (
    .A(data_reg[2]),
    .B(data_in[2]),
    .S(_167_),
    .Y(_170_)
  );
  INVX1 _417_ (
    .A(_170_),
    .Y(_010_)
  );
  MUX2X1 _418_ (
    .A(data_reg[3]),
    .B(data_in[3]),
    .S(_167_),
    .Y(_171_)
  );
  INVX1 _419_ (
    .A(_171_),
    .Y(_011_)
  );
  MUX2X1 _420_ (
    .A(data_reg[4]),
    .B(data_in[4]),
    .S(_167_),
    .Y(_172_)
  );
  INVX1 _421_ (
    .A(_172_),
    .Y(_012_)
  );
  MUX2X1 _422_ (
    .A(data_reg[5]),
    .B(data_in[5]),
    .S(_167_),
    .Y(_173_)
  );
  INVX1 _423_ (
    .A(_173_),
    .Y(_013_)
  );
  MUX2X1 _424_ (
    .A(data_reg[6]),
    .B(data_in[6]),
    .S(_167_),
    .Y(_174_)
  );
  INVX1 _425_ (
    .A(_174_),
    .Y(_014_)
  );
  MUX2X1 _426_ (
    .A(data_reg[7]),
    .B(data_in[7]),
    .S(_167_),
    .Y(_175_)
  );
  INVX1 _427_ (
    .A(_175_),
    .Y(_015_)
  );
  OAI21X1 _428_ (
    .A(_067_),
    .B(_088_),
    .C(_167_),
    .Y(_016_)
  );
  OAI21X1 _429_ (
    .A(state[1]),
    .B(start),
    .C(_088_),
    .Y(_176_)
  );
  NAND2X1 _430_ (
    .A(_095_),
    .B(_176_),
    .Y(_177_)
  );
  OAI21X1 _431_ (
    .A(bit_cnt[3]),
    .B(_127_),
    .C(_094_),
    .Y(_178_)
  );
  NAND3X1 _432_ (
    .A(_123_),
    .B(_177_),
    .C(_178_),
    .Y(_179_)
  );
  OR2X1 _433_ (
    .A(_095_),
    .B(_121_),
    .Y(_180_)
  );
  MUX2X1 _434_ (
    .A(data_reg[7]),
    .B(data_reg[5]),
    .S(bit_cnt[1]),
    .Y(_181_)
  );
  MUX2X1 _435_ (
    .A(data_reg[4]),
    .B(data_reg[6]),
    .S(bit_cnt[1]),
    .Y(_182_)
  );
  MUX2X1 _436_ (
    .A(_181_),
    .B(_182_),
    .S(bit_cnt[0]),
    .Y(_183_)
  );
  MUX2X1 _437_ (
    .A(data_reg[3]),
    .B(data_reg[1]),
    .S(bit_cnt[1]),
    .Y(_184_)
  );
  MUX2X1 _438_ (
    .A(data_reg[0]),
    .B(data_reg[2]),
    .S(bit_cnt[1]),
    .Y(_185_)
  );
  MUX2X1 _439_ (
    .A(_184_),
    .B(_185_),
    .S(bit_cnt[0]),
    .Y(_186_)
  );
  MUX2X1 _440_ (
    .A(_186_),
    .B(_183_),
    .S(_143_),
    .Y(_187_)
  );
  OR2X1 _441_ (
    .A(_156_),
    .B(_187_),
    .Y(_188_)
  );
  AOI22X1 _442_ (
    .A(data_in[7]),
    .B(_166_),
    .C(_179_),
    .D(mosi),
    .Y(_189_)
  );
  OAI21X1 _443_ (
    .A(_180_),
    .B(_188_),
    .C(_189_),
    .Y(_017_)
  );
  NAND2X1 _444_ (
    .A(clk_cnt[0]),
    .B(state[1]),
    .Y(_190_)
  );
  OAI21X1 _445_ (
    .A(clk_cnt[0]),
    .B(_123_),
    .C(_190_),
    .Y(_018_)
  );
  XOR2X1 _446_ (
    .A(clk_cnt[0]),
    .B(clk_cnt[1]),
    .Y(_191_)
  );
  AOI22X1 _447_ (
    .A(clk_cnt[1]),
    .B(state[1]),
    .C(_122_),
    .D(_191_),
    .Y(_192_)
  );
  INVX1 _448_ (
    .A(_192_),
    .Y(_019_)
  );
  NAND2X1 _449_ (
    .A(clk_cnt[2]),
    .B(state[1]),
    .Y(_193_)
  );
  NAND3X1 _450_ (
    .A(clk_cnt[0]),
    .B(clk_cnt[1]),
    .C(clk_cnt[2]),
    .Y(_194_)
  );
  NAND2X1 _451_ (
    .A(_103_),
    .B(_194_),
    .Y(_195_)
  );
  OAI21X1 _452_ (
    .A(_123_),
    .B(_195_),
    .C(_193_),
    .Y(_020_)
  );
  NOR2X1 _453_ (
    .A(_068_),
    .B(_194_),
    .Y(_196_)
  );
  XNOR2X1 _454_ (
    .A(clk_cnt[3]),
    .B(_194_),
    .Y(_197_)
  );
  AOI22X1 _455_ (
    .A(clk_cnt[3]),
    .B(state[1]),
    .C(_122_),
    .D(_197_),
    .Y(_198_)
  );
  INVX1 _456_ (
    .A(_198_),
    .Y(_021_)
  );
  NOR3X1 _457_ (
    .A(_068_),
    .B(_069_),
    .C(_194_),
    .Y(_199_)
  );
  NOR2X1 _458_ (
    .A(clk_cnt[4]),
    .B(_196_),
    .Y(_200_)
  );
  NOR2X1 _459_ (
    .A(_199_),
    .B(_200_),
    .Y(_201_)
  );
  AOI22X1 _460_ (
    .A(clk_cnt[4]),
    .B(state[1]),
    .C(_122_),
    .D(_201_),
    .Y(_202_)
  );
  INVX1 _461_ (
    .A(_202_),
    .Y(_022_)
  );
  AND2X1 _462_ (
    .A(clk_cnt[5]),
    .B(_199_),
    .Y(_203_)
  );
  NOR2X1 _463_ (
    .A(clk_cnt[5]),
    .B(_199_),
    .Y(_204_)
  );
  NOR2X1 _464_ (
    .A(_203_),
    .B(_204_),
    .Y(_205_)
  );
  AOI22X1 _465_ (
    .A(clk_cnt[5]),
    .B(state[1]),
    .C(_122_),
    .D(_205_),
    .Y(_206_)
  );
  INVX1 _466_ (
    .A(_206_),
    .Y(_023_)
  );
  AND2X1 _467_ (
    .A(clk_cnt[6]),
    .B(_203_),
    .Y(_207_)
  );
  NAND3X1 _468_ (
    .A(clk_cnt[5]),
    .B(clk_cnt[6]),
    .C(_199_),
    .Y(_208_)
  );
  XOR2X1 _469_ (
    .A(clk_cnt[6]),
    .B(_203_),
    .Y(_209_)
  );
  AOI22X1 _470_ (
    .A(clk_cnt[6]),
    .B(state[1]),
    .C(_122_),
    .D(_209_),
    .Y(_210_)
  );
  INVX1 _471_ (
    .A(_210_),
    .Y(_024_)
  );
  NOR2X1 _472_ (
    .A(_070_),
    .B(_208_),
    .Y(_211_)
  );
  OAI22X1 _473_ (
    .A(_070_),
    .B(_089_),
    .C(_123_),
    .D(_211_),
    .Y(_212_)
  );
  OAI21X1 _474_ (
    .A(clk_cnt[7]),
    .B(_207_),
    .C(_212_),
    .Y(_213_)
  );
  INVX1 _475_ (
    .A(_213_),
    .Y(_025_)
  );
  NOR3X1 _476_ (
    .A(_070_),
    .B(_071_),
    .C(_208_),
    .Y(_214_)
  );
  NAND2X1 _477_ (
    .A(clk_cnt[8]),
    .B(_211_),
    .Y(_215_)
  );
  NOR2X1 _478_ (
    .A(_123_),
    .B(_214_),
    .Y(_216_)
  );
  OAI21X1 _479_ (
    .A(clk_cnt[8]),
    .B(_211_),
    .C(_216_),
    .Y(_217_)
  );
  OAI21X1 _480_ (
    .A(_071_),
    .B(_089_),
    .C(_217_),
    .Y(_026_)
  );
  NOR2X1 _481_ (
    .A(_072_),
    .B(_215_),
    .Y(_218_)
  );
  NOR2X1 _482_ (
    .A(_123_),
    .B(_218_),
    .Y(_219_)
  );
  OAI21X1 _483_ (
    .A(clk_cnt[9]),
    .B(_214_),
    .C(_219_),
    .Y(_220_)
  );
  OAI21X1 _484_ (
    .A(_072_),
    .B(_089_),
    .C(_220_),
    .Y(_027_)
  );
  NAND2X1 _485_ (
    .A(clk_cnt[10]),
    .B(state[1]),
    .Y(_221_)
  );
  AND2X1 _486_ (
    .A(clk_cnt[10]),
    .B(_218_),
    .Y(_222_)
  );
  NAND3X1 _487_ (
    .A(clk_cnt[9]),
    .B(clk_cnt[10]),
    .C(_214_),
    .Y(_223_)
  );
  OAI21X1 _488_ (
    .A(_123_),
    .B(_222_),
    .C(_221_),
    .Y(_224_)
  );
  OAI21X1 _489_ (
    .A(clk_cnt[10]),
    .B(_218_),
    .C(_224_),
    .Y(_225_)
  );
  INVX1 _490_ (
    .A(_225_),
    .Y(_028_)
  );
  NOR2X1 _491_ (
    .A(_073_),
    .B(_223_),
    .Y(_226_)
  );
  OAI21X1 _492_ (
    .A(clk_cnt[11]),
    .B(_222_),
    .C(_122_),
    .Y(_227_)
  );
  OAI22X1 _493_ (
    .A(_073_),
    .B(_089_),
    .C(_226_),
    .D(_227_),
    .Y(_029_)
  );
  NOR3X1 _494_ (
    .A(_073_),
    .B(_074_),
    .C(_223_),
    .Y(_228_)
  );
  NAND2X1 _495_ (
    .A(clk_cnt[12]),
    .B(_226_),
    .Y(_229_)
  );
  OAI21X1 _496_ (
    .A(clk_cnt[12]),
    .B(_226_),
    .C(_122_),
    .Y(_230_)
  );
  OAI22X1 _497_ (
    .A(_074_),
    .B(_089_),
    .C(_228_),
    .D(_230_),
    .Y(_030_)
  );
  NOR2X1 _498_ (
    .A(_075_),
    .B(_229_),
    .Y(_231_)
  );
  NOR2X1 _499_ (
    .A(_123_),
    .B(_231_),
    .Y(_232_)
  );
  OAI21X1 _500_ (
    .A(clk_cnt[13]),
    .B(_228_),
    .C(_232_),
    .Y(_233_)
  );
  OAI21X1 _501_ (
    .A(_075_),
    .B(_089_),
    .C(_233_),
    .Y(_031_)
  );
  NAND2X1 _502_ (
    .A(clk_cnt[14]),
    .B(state[1]),
    .Y(_234_)
  );
  NAND3X1 _503_ (
    .A(clk_cnt[13]),
    .B(clk_cnt[14]),
    .C(_228_),
    .Y(_235_)
  );
  INVX1 _504_ (
    .A(_235_),
    .Y(_236_)
  );
  OAI21X1 _505_ (
    .A(clk_cnt[14]),
    .B(_231_),
    .C(_122_),
    .Y(_237_)
  );
  OAI21X1 _506_ (
    .A(_236_),
    .B(_237_),
    .C(_234_),
    .Y(_032_)
  );
  NOR2X1 _507_ (
    .A(_076_),
    .B(_235_),
    .Y(_238_)
  );
  OAI21X1 _508_ (
    .A(clk_cnt[15]),
    .B(_236_),
    .C(_122_),
    .Y(_239_)
  );
  OAI22X1 _509_ (
    .A(_076_),
    .B(_089_),
    .C(_238_),
    .D(_239_),
    .Y(_033_)
  );
  AOI21X1 _510_ (
    .A(_122_),
    .B(_238_),
    .C(clk_cnt[16]),
    .Y(_240_)
  );
  NOR3X1 _511_ (
    .A(_076_),
    .B(_077_),
    .C(_235_),
    .Y(_241_)
  );
  NAND2X1 _512_ (
    .A(clk_cnt[16]),
    .B(_238_),
    .Y(_242_)
  );
  AOI21X1 _513_ (
    .A(_122_),
    .B(_242_),
    .C(state[1]),
    .Y(_243_)
  );
  NOR2X1 _514_ (
    .A(_240_),
    .B(_243_),
    .Y(_034_)
  );
  NAND3X1 _515_ (
    .A(_078_),
    .B(_122_),
    .C(_241_),
    .Y(_244_)
  );
  OAI21X1 _516_ (
    .A(_078_),
    .B(_243_),
    .C(_244_),
    .Y(_035_)
  );
  NAND2X1 _517_ (
    .A(clk_cnt[18]),
    .B(state[1]),
    .Y(_245_)
  );
  NOR2X1 _518_ (
    .A(_078_),
    .B(_242_),
    .Y(_246_)
  );
  AND2X1 _519_ (
    .A(clk_cnt[18]),
    .B(_246_),
    .Y(_247_)
  );
  NAND3X1 _520_ (
    .A(clk_cnt[17]),
    .B(clk_cnt[18]),
    .C(_241_),
    .Y(_248_)
  );
  OAI21X1 _521_ (
    .A(clk_cnt[18]),
    .B(_246_),
    .C(_122_),
    .Y(_249_)
  );
  OAI21X1 _522_ (
    .A(_247_),
    .B(_249_),
    .C(_245_),
    .Y(_036_)
  );
  NOR2X1 _523_ (
    .A(_079_),
    .B(_248_),
    .Y(_250_)
  );
  OAI21X1 _524_ (
    .A(clk_cnt[19]),
    .B(_247_),
    .C(_122_),
    .Y(_251_)
  );
  OAI22X1 _525_ (
    .A(_079_),
    .B(_089_),
    .C(_250_),
    .D(_251_),
    .Y(_037_)
  );
  NOR3X1 _526_ (
    .A(_079_),
    .B(_080_),
    .C(_248_),
    .Y(_252_)
  );
  OAI21X1 _527_ (
    .A(clk_cnt[20]),
    .B(_250_),
    .C(_122_),
    .Y(_253_)
  );
  OAI22X1 _528_ (
    .A(_080_),
    .B(_089_),
    .C(_252_),
    .D(_253_),
    .Y(_038_)
  );
  AND2X1 _529_ (
    .A(clk_cnt[21]),
    .B(_252_),
    .Y(_254_)
  );
  NOR2X1 _530_ (
    .A(_123_),
    .B(_254_),
    .Y(_255_)
  );
  OAI21X1 _531_ (
    .A(clk_cnt[21]),
    .B(_252_),
    .C(_255_),
    .Y(_256_)
  );
  OAI21X1 _532_ (
    .A(_081_),
    .B(_089_),
    .C(_256_),
    .Y(_039_)
  );
  NAND2X1 _533_ (
    .A(clk_cnt[22]),
    .B(state[1]),
    .Y(_257_)
  );
  NAND3X1 _534_ (
    .A(clk_cnt[21]),
    .B(clk_cnt[22]),
    .C(_252_),
    .Y(_258_)
  );
  INVX1 _535_ (
    .A(_258_),
    .Y(_259_)
  );
  OAI21X1 _536_ (
    .A(clk_cnt[22]),
    .B(_254_),
    .C(_122_),
    .Y(_260_)
  );
  OAI21X1 _537_ (
    .A(_259_),
    .B(_260_),
    .C(_257_),
    .Y(_040_)
  );
  NOR2X1 _538_ (
    .A(_082_),
    .B(_258_),
    .Y(_261_)
  );
  OAI21X1 _539_ (
    .A(clk_cnt[23]),
    .B(_259_),
    .C(_122_),
    .Y(_262_)
  );
  OAI22X1 _540_ (
    .A(_082_),
    .B(_089_),
    .C(_261_),
    .D(_262_),
    .Y(_041_)
  );
  NOR3X1 _541_ (
    .A(_082_),
    .B(_083_),
    .C(_258_),
    .Y(_263_)
  );
  OAI21X1 _542_ (
    .A(clk_cnt[24]),
    .B(_261_),
    .C(_122_),
    .Y(_264_)
  );
  OAI22X1 _543_ (
    .A(_083_),
    .B(_089_),
    .C(_263_),
    .D(_264_),
    .Y(_042_)
  );
  AND2X1 _544_ (
    .A(clk_cnt[25]),
    .B(_263_),
    .Y(_265_)
  );
  OAI21X1 _545_ (
    .A(clk_cnt[25]),
    .B(_263_),
    .C(_122_),
    .Y(_266_)
  );
  OAI22X1 _546_ (
    .A(_084_),
    .B(_089_),
    .C(_265_),
    .D(_266_),
    .Y(_043_)
  );
  NAND2X1 _547_ (
    .A(clk_cnt[26]),
    .B(state[1]),
    .Y(_267_)
  );
  AND2X1 _548_ (
    .A(clk_cnt[26]),
    .B(_265_),
    .Y(_268_)
  );
  NAND3X1 _549_ (
    .A(clk_cnt[25]),
    .B(clk_cnt[26]),
    .C(_263_),
    .Y(_269_)
  );
  OAI21X1 _550_ (
    .A(clk_cnt[26]),
    .B(_265_),
    .C(_122_),
    .Y(_270_)
  );
  OAI21X1 _551_ (
    .A(_268_),
    .B(_270_),
    .C(_267_),
    .Y(_044_)
  );
  NOR2X1 _552_ (
    .A(_085_),
    .B(_269_),
    .Y(_271_)
  );
  OAI21X1 _553_ (
    .A(clk_cnt[27]),
    .B(_268_),
    .C(_122_),
    .Y(_272_)
  );
  OAI22X1 _554_ (
    .A(_085_),
    .B(_089_),
    .C(_271_),
    .D(_272_),
    .Y(_045_)
  );
  NOR3X1 _555_ (
    .A(_085_),
    .B(_086_),
    .C(_269_),
    .Y(_273_)
  );
  OAI21X1 _556_ (
    .A(clk_cnt[28]),
    .B(_271_),
    .C(_122_),
    .Y(_274_)
  );
  OAI22X1 _557_ (
    .A(_086_),
    .B(_089_),
    .C(_273_),
    .D(_274_),
    .Y(_046_)
  );
  NAND2X1 _558_ (
    .A(clk_cnt[29]),
    .B(state[1]),
    .Y(_275_)
  );
  AND2X1 _559_ (
    .A(clk_cnt[29]),
    .B(_273_),
    .Y(_276_)
  );
  OAI21X1 _560_ (
    .A(clk_cnt[29]),
    .B(_273_),
    .C(_122_),
    .Y(_277_)
  );
  OAI21X1 _561_ (
    .A(_276_),
    .B(_277_),
    .C(_275_),
    .Y(_047_)
  );
  NAND2X1 _562_ (
    .A(clk_cnt[30]),
    .B(state[1]),
    .Y(_278_)
  );
  NOR2X1 _563_ (
    .A(clk_cnt[30]),
    .B(_276_),
    .Y(_279_)
  );
  NAND3X1 _564_ (
    .A(clk_cnt[29]),
    .B(clk_cnt[30]),
    .C(_273_),
    .Y(_280_)
  );
  NAND2X1 _565_ (
    .A(_122_),
    .B(_280_),
    .Y(_281_)
  );
  OAI21X1 _566_ (
    .A(_279_),
    .B(_281_),
    .C(_278_),
    .Y(_048_)
  );
  AOI21X1 _567_ (
    .A(state[0]),
    .B(_280_),
    .C(state[1]),
    .Y(_282_)
  );
  NOR2X1 _568_ (
    .A(_087_),
    .B(_282_),
    .Y(_049_)
  );
  NAND2X1 _569_ (
    .A(_088_),
    .B(state[1]),
    .Y(_283_)
  );
  INVX1 _570_ (
    .A(_283_),
    .Y(_302_[0])
  );
  MUX2X1 _571_ (
    .A(data_out[0]),
    .B(shift_rx[0]),
    .S(_283_),
    .Y(_284_)
  );
  INVX1 _572_ (
    .A(_284_),
    .Y(_050_)
  );
  MUX2X1 _573_ (
    .A(data_out[1]),
    .B(shift_rx[1]),
    .S(_283_),
    .Y(_285_)
  );
  INVX1 _574_ (
    .A(_285_),
    .Y(_051_)
  );
  MUX2X1 _575_ (
    .A(data_out[2]),
    .B(shift_rx[2]),
    .S(_283_),
    .Y(_286_)
  );
  INVX1 _576_ (
    .A(_286_),
    .Y(_052_)
  );
  MUX2X1 _577_ (
    .A(data_out[3]),
    .B(shift_rx[3]),
    .S(_283_),
    .Y(_287_)
  );
  INVX1 _578_ (
    .A(_287_),
    .Y(_053_)
  );
  MUX2X1 _579_ (
    .A(data_out[4]),
    .B(shift_rx[4]),
    .S(_283_),
    .Y(_288_)
  );
  INVX1 _580_ (
    .A(_288_),
    .Y(_054_)
  );
  MUX2X1 _581_ (
    .A(data_out[5]),
    .B(shift_rx[5]),
    .S(_283_),
    .Y(_289_)
  );
  INVX1 _582_ (
    .A(_289_),
    .Y(_055_)
  );
  MUX2X1 _583_ (
    .A(data_out[6]),
    .B(shift_rx[6]),
    .S(_283_),
    .Y(_290_)
  );
  INVX1 _584_ (
    .A(_290_),
    .Y(_056_)
  );
  MUX2X1 _585_ (
    .A(data_out[7]),
    .B(shift_rx[7]),
    .S(_283_),
    .Y(_291_)
  );
  INVX1 _586_ (
    .A(_291_),
    .Y(_057_)
  );
  AOI22X1 _587_ (
    .A(done_flag),
    .B(_094_),
    .C(_165_),
    .D(_088_),
    .Y(_058_)
  );
  OAI21X1 _588_ (
    .A(state[1]),
    .B(done_flag),
    .C(state[0]),
    .Y(_292_)
  );
  INVX1 _589_ (
    .A(_292_),
    .Y(_059_)
  );
  OR2X1 _590_ (
    .A(bit_cnt[3]),
    .B(_180_),
    .Y(_293_)
  );
  NAND3X1 _591_ (
    .A(_124_),
    .B(_131_),
    .C(_178_),
    .Y(_294_)
  );
  NAND2X1 _592_ (
    .A(bit_cnt[0]),
    .B(_294_),
    .Y(_295_)
  );
  OAI21X1 _593_ (
    .A(bit_cnt[0]),
    .B(_293_),
    .C(_295_),
    .Y(_060_)
  );
  NAND2X1 _594_ (
    .A(bit_cnt[1]),
    .B(_294_),
    .Y(_296_)
  );
  OAI21X1 _595_ (
    .A(_138_),
    .B(_180_),
    .C(_296_),
    .Y(_061_)
  );
  NAND2X1 _596_ (
    .A(bit_cnt[2]),
    .B(_294_),
    .Y(_297_)
  );
  OAI21X1 _597_ (
    .A(_144_),
    .B(_293_),
    .C(_297_),
    .Y(_062_)
  );
  AND2X1 _598_ (
    .A(bit_cnt[3]),
    .B(_294_),
    .Y(_063_)
  );
  OAI21X1 _599_ (
    .A(_088_),
    .B(cs_n),
    .C(_167_),
    .Y(_298_)
  );
  INVX1 _600_ (
    .A(_298_),
    .Y(_064_)
  );
  OAI21X1 _601_ (
    .A(state[1]),
    .B(_121_),
    .C(state[0]),
    .Y(_299_)
  );
  OAI21X1 _602_ (
    .A(_091_),
    .B(_299_),
    .C(_132_),
    .Y(_065_)
  );
  OAI21X1 _603_ (
    .A(sclk),
    .B(_129_),
    .C(_094_),
    .Y(_300_)
  );
  AND2X1 _604_ (
    .A(_299_),
    .B(_300_),
    .Y(_301_)
  );
  OAI21X1 _605_ (
    .A(_092_),
    .B(_301_),
    .C(_135_),
    .Y(_066_)
  );
  DFFSR _606_ (
    .CLK(clk),
    .D(_000_),
    .Q(shift_rx[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _607_ (
    .CLK(clk),
    .D(_001_),
    .Q(shift_rx[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _608_ (
    .CLK(clk),
    .D(_002_),
    .Q(shift_rx[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _609_ (
    .CLK(clk),
    .D(_003_),
    .Q(shift_rx[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _610_ (
    .CLK(clk),
    .D(_004_),
    .Q(shift_rx[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _611_ (
    .CLK(clk),
    .D(_005_),
    .Q(shift_rx[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _612_ (
    .CLK(clk),
    .D(_006_),
    .Q(shift_rx[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _613_ (
    .CLK(clk),
    .D(_007_),
    .Q(shift_rx[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _614_ (
    .CLK(clk),
    .D(_008_),
    .Q(data_reg[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _615_ (
    .CLK(clk),
    .D(_009_),
    .Q(data_reg[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _616_ (
    .CLK(clk),
    .D(_010_),
    .Q(data_reg[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _617_ (
    .CLK(clk),
    .D(_011_),
    .Q(data_reg[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _618_ (
    .CLK(clk),
    .D(_012_),
    .Q(data_reg[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _619_ (
    .CLK(clk),
    .D(_013_),
    .Q(data_reg[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _620_ (
    .CLK(clk),
    .D(_014_),
    .Q(data_reg[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _621_ (
    .CLK(clk),
    .D(_015_),
    .Q(data_reg[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _622_ (
    .CLK(clk),
    .D(_016_),
    .Q(busy),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _623_ (
    .CLK(clk),
    .D(_017_),
    .Q(mosi),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _624_ (
    .CLK(clk),
    .D(_018_),
    .Q(clk_cnt[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _625_ (
    .CLK(clk),
    .D(_019_),
    .Q(clk_cnt[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _626_ (
    .CLK(clk),
    .D(_020_),
    .Q(clk_cnt[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _627_ (
    .CLK(clk),
    .D(_021_),
    .Q(clk_cnt[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _628_ (
    .CLK(clk),
    .D(_022_),
    .Q(clk_cnt[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _629_ (
    .CLK(clk),
    .D(_023_),
    .Q(clk_cnt[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _630_ (
    .CLK(clk),
    .D(_024_),
    .Q(clk_cnt[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _631_ (
    .CLK(clk),
    .D(_025_),
    .Q(clk_cnt[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _632_ (
    .CLK(clk),
    .D(_026_),
    .Q(clk_cnt[8]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _633_ (
    .CLK(clk),
    .D(_027_),
    .Q(clk_cnt[9]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _634_ (
    .CLK(clk),
    .D(_028_),
    .Q(clk_cnt[10]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _635_ (
    .CLK(clk),
    .D(_029_),
    .Q(clk_cnt[11]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _636_ (
    .CLK(clk),
    .D(_030_),
    .Q(clk_cnt[12]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _637_ (
    .CLK(clk),
    .D(_031_),
    .Q(clk_cnt[13]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _638_ (
    .CLK(clk),
    .D(_032_),
    .Q(clk_cnt[14]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _639_ (
    .CLK(clk),
    .D(_033_),
    .Q(clk_cnt[15]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _640_ (
    .CLK(clk),
    .D(_034_),
    .Q(clk_cnt[16]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _641_ (
    .CLK(clk),
    .D(_035_),
    .Q(clk_cnt[17]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _642_ (
    .CLK(clk),
    .D(_036_),
    .Q(clk_cnt[18]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _643_ (
    .CLK(clk),
    .D(_037_),
    .Q(clk_cnt[19]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _644_ (
    .CLK(clk),
    .D(_038_),
    .Q(clk_cnt[20]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _645_ (
    .CLK(clk),
    .D(_039_),
    .Q(clk_cnt[21]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _646_ (
    .CLK(clk),
    .D(_040_),
    .Q(clk_cnt[22]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _647_ (
    .CLK(clk),
    .D(_041_),
    .Q(clk_cnt[23]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _648_ (
    .CLK(clk),
    .D(_042_),
    .Q(clk_cnt[24]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _649_ (
    .CLK(clk),
    .D(_043_),
    .Q(clk_cnt[25]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _650_ (
    .CLK(clk),
    .D(_044_),
    .Q(clk_cnt[26]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _651_ (
    .CLK(clk),
    .D(_045_),
    .Q(clk_cnt[27]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _652_ (
    .CLK(clk),
    .D(_046_),
    .Q(clk_cnt[28]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _653_ (
    .CLK(clk),
    .D(_047_),
    .Q(clk_cnt[29]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _654_ (
    .CLK(clk),
    .D(_048_),
    .Q(clk_cnt[30]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _655_ (
    .CLK(clk),
    .D(_049_),
    .Q(clk_cnt[31]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _656_ (
    .CLK(clk),
    .D(_050_),
    .Q(data_out[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _657_ (
    .CLK(clk),
    .D(_051_),
    .Q(data_out[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _658_ (
    .CLK(clk),
    .D(_052_),
    .Q(data_out[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _659_ (
    .CLK(clk),
    .D(_053_),
    .Q(data_out[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _660_ (
    .CLK(clk),
    .D(_054_),
    .Q(data_out[4]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _661_ (
    .CLK(clk),
    .D(_055_),
    .Q(data_out[5]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _662_ (
    .CLK(clk),
    .D(_056_),
    .Q(data_out[6]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _663_ (
    .CLK(clk),
    .D(_057_),
    .Q(data_out[7]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _664_ (
    .CLK(clk),
    .D(_302_[0]),
    .Q(done),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _665_ (
    .CLK(clk),
    .D(_058_),
    .Q(state[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _666_ (
    .CLK(clk),
    .D(_059_),
    .Q(state[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _667_ (
    .CLK(clk),
    .D(_060_),
    .Q(bit_cnt[0]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _668_ (
    .CLK(clk),
    .D(_061_),
    .Q(bit_cnt[1]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _669_ (
    .CLK(clk),
    .D(_062_),
    .Q(bit_cnt[2]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _670_ (
    .CLK(clk),
    .D(_063_),
    .Q(bit_cnt[3]),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _671_ (
    .CLK(clk),
    .D(_064_),
    .Q(cs_n),
    .R(1'h1),
    .S(rst_n)
  );
  DFFSR _672_ (
    .CLK(clk),
    .D(_065_),
    .Q(sclk),
    .R(rst_n),
    .S(1'h1)
  );
  DFFSR _673_ (
    .CLK(clk),
    .D(_066_),
    .Q(done_flag),
    .R(rst_n),
    .S(1'h1)
  );
endmodule
