/* Generated by Yosys 0.58+35 (git sha1 89f32a415, g++ 11.4.0-1ubuntu1~22.04.2 -fPIC -O3) */

module spi_slave(sclk, cs_n, mosi, miso, tx_data, rx_data, rx_ready);
  input sclk;
  wire sclk;
  input cs_n;
  wire cs_n;
  input mosi;
  wire mosi;
  output miso;
  reg miso;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  output [7:0] rx_data;
  wire [7:0] rx_data;
  output rx_ready;
  wire rx_ready;
  wire _0_;
  wire _1_;
  wire _2_;
  wire [31:0] bit_cnt;
  wire [7:0] send_data;
  wire [7:0] shift_rx;
  INVX1 _3_ (
    .A(send_data[6]),
    .Y(_1_)
  );
  NAND2X1 _4_ (
    .A(miso),
    .B(cs_n),
    .Y(_2_)
  );
  OAI21X1 _5_ (
    .A(_1_),
    .B(cs_n),
    .C(_2_),
    .Y(_0_)
  );
  DFFNEGX1 _6_ (
    .CLK(sclk),
    .D(_0_),
    .Q(miso)
  );
  always @(posedge cs_n, negedge cs_n)
    if (!cs_n) miso <= tx_data[7];
    else miso <= 1'h0;
  DFFSR _8_ (
    .CLK(cs_n),
    .D(1'h1),
    .Q(rx_ready),
    .R(cs_n),
    .S(1'h1)
  );
  reg \send_data_reg[6] ;
  always @*
    if (!cs_n) \send_data_reg[6]  = tx_data[6];
  assign send_data[6] = \send_data_reg[6] ;
  assign bit_cnt = 32'd0;
  assign rx_data = 8'h00;
  assign shift_rx = 8'h00;
endmodule
